name = "nullrose-main"
compatibility_date = "2025-01-01"
main = "_worker.js"

[build]
command = "mkdir -p dist && cp -r index.html nullrose pl agata rate README.md .nojekyll robots.txt _headers dist/"

[assets]
directory = "./dist"
